@startuml
Application o-> Adder

class Application {
    + createOutput();
    + printOutput();
}

class Adder {
    + readNum // loop 5 times
    + userInput // assign inputs to array
    + addNumbers
}
@enduml